[tool.black]
line-length = 88
target-version = ['py37']
#extend-exclude = '''
#/(
  # The following are specific to Black, you probably don't want those.
 # | folder_to_ignore_1
  #| folder_to_ignore_2
#)/
#'''
